# Generated by Django 2.0 on 2020-05-04 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG_POSTS', '0003_auto_20200503_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='photo_main',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_date',
        ),
    ]
