# Generated by Django 2.0 on 2020-05-10 22:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG_POSTS', '0004_auto_20200503_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
